language: php

sudo: true

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.6
    - php: 5.6
      env: deps=low
    - php: 7.0
    - php: 7.0
      env: deps=low
    - php: 7.1
    - php: hhvm
    - php: nightly
    - php: nightly
      env: deps=low

before_script:
  # create logs dir
  - mkdir -p build/logs

  # prepare scripts
  - chmod a+x ./tests/ci/*.sh

  # installing web server
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo a2enmod rewrite actions fastcgi alias ssl

  # prepare server certificate
  - openssl genrsa 1024 > server.key
  - openssl req -batch -subj '/CN=127.0.0.1' -new -x509 -nodes -sha1 -days 3650 -key server.key > server.crt

  # enable php-fpm
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." || $TRAVIS_PHP_VERSION == "nightly" ]]; then cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf; fi
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm; fi

  # Starting webserver
  - if [ "$TRAVIS_PHP_VERSION" == 'hhvm' ]; then ./tests/ci/configure-apache-hhvm.sh; fi
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then ./tests/ci/configure-apache.sh; fi

  # prepare composer and dependencies
  - composer self-update
  - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest; fi
  - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then vendor/bin/coveralls --no-interaction; fi

after_failure:
  - cat /tmp/hhvm.log
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/apache2/access.log
  - sudo cat /var/log/apache2/other_vhosts_access.log
