language: php

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-stable
  include:
    - php: hhvm-stable
    - php: hhvm-stable
      env: deps=low
    - php: 7.0
    - php: 7.0
      env: deps=low
    - php: 7.1
    - php: nightly
    - php: nightly
      env: deps=low

before_install:
  - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi
  - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install:
  # install dependencies
  - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest; fi
  - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
  - ./vendor/bin/behat --suite client
