language: php

sudo: true

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm
    include:
        - php: 5.6
        - php: 5.6
          env: deps=low
        - php: 7.0
        - php: 7.0
          env: deps=low
        - php: 7.1
        - php: hhvm
        - php: nightly
        - php: nightly
          env: deps=low

before_script:
    - mkdir -p build/logs
    - sudo chmod -R 0777 build/logs
    - sudo apt-get update > /dev/null
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi > /dev/null
    # enable php-fpm
    - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias ssl
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # prepare server certificate
    - openssl genrsa 1024 > server.key
    - openssl req -batch -subj '/CN=127.0.0.1' -new -x509 -nodes -sha1 -days 3650 -key server.key > server.crt
    # configure apache virtual hosts
    - sudo cp -f tests/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo /etc/init.d/apache2 restart || (sudo cat /var/log/apache2/error.log && exit 1)
    - composer self-update
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 
after_success:
    - vendor/bin/coveralls --no-interaction

after_failure:
    - cat build/logs/apache-access.log
    - cat build/logs/apache-error.log
    - cat build/logs/cgi.log
    - sudo cat /var/log/apache2/access.log
    - sudo cat /var/log/apache2/error.log
